name: update-page

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish
        env:
          OSS_CONFIG: ${{ secrets.OSS_CONFIG }}
          OSS_NAME: ${{ secrets.OSS_NAME }}
        run: |
          sudo apt update
          sudo pip3 install setuptools
          sudo pip3 install -r requirements.txt
          cd ..
          sphinx-build -b html luatos-wiki output -E
          wget http://gosspublic.alicdn.com/ossutil/1.7.1/ossutil64
          sudo chmod 755 ossutil64
          echo -e "${OSS_CONFIG}" > ~/.ossutilconfig
          ./ossutil64 cp -r output/ oss://${OSS_NAME}/


